### ISSUE TITLE
Row Dragging not working in vue examples

### ISSUE THREAD

**Issue by lhilton** [ag-grid/ag-grid-vue#18] opened 2018-04-06 23:26 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ag-grid/ag-grid-vue/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Rows not draggable after defining column as draggable with the rowDrag: true attribute. I used the ag-grid-vue-examples library to reproduce. You will find my code at the end of this report.

**Expected behavior**
Row will be draggable

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**
Current (as of today) version of [ag-grid-vue-example](https://github.com/ag-grid/ag-grid-vue-example), built with npm 5.6.0

* **ag-grid-vue version:** 2.0.X
Using v 17.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
Using v 17.0.0

* **VueJS version:** 2.0.X
Using v 2.5.16

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Confirmed on FF 59.0.2 and Chrome 65.0.3325.181

> Edited from ag-grid-vue-examples/src/editor-component-example/EditorComponentExample.vue

```vue
<template>
    <div style="width: 900px;">
        <ag-grid-vue style="width: 100%; height: 350px;" class="ag-fresh"
                     :gridOptions="gridOptions">
        </ag-grid-vue>
    </div>
</template>

<script>
    import Vue from "vue";
    import {AgGridVue} from "ag-grid-vue";
    import MoodRendererComponent from './MoodRendererComponent'
    import MoodEditorComponent from './MoodEditorComponent.vue'
    import NumericEditorComponent from './NumericEditorComponent'

    export default {
        data () {
            return {
                gridOptions: null
            }
        },
        components: {
            'ag-grid-vue': AgGridVue
        },
        methods: {
            createRowData() {
                return [
                    {name: "Bob", mood: "Happy", number: 10},
                    {name: "Harry", mood: "Sad", number: 3},
                    {name: "Sally", mood: "Happy", number: 20},
                    {name: "Mary", mood: "Sad", number: 5},
                    {name: "John", mood: "Happy", number: 15},
                    {name: "Jack", mood: "Happy", number: 25},
                    {name: "Sue", mood: "Sad", number: 43},
                    {name: "Sean", mood: "Sad", number: 1335},
                    {name: "Niall", mood: "Happy", number: 2},
                    {name: "Alberto", mood: "Happy", number: 123},
                    {name: "Fred", mood: "Sad", number: 532},
                    {name: "Jenny", mood: "Happy", number: 34},
                    {name: "Larry", mood: "Happy", number: 13},
                ];
            },
            createColumnDefs() {
                return [
                    {headerName: "Name", field: "name", width: 300, rowDrag: true},
                    {
                        headerName: "Mood",
                        field: "mood",
                        cellRendererFramework: MoodRendererComponent,
                        cellEditorFramework: MoodEditorComponent,
                        editable: true,
                        width: 300
                    },
                    {
                        headerName: "Numeric",
                        field: "number",
                        cellEditorFramework: NumericEditorComponent,
                        editable: true,
                        width: 280
                    }
                ]
            }
        },
        beforeMount() {
            this.gridOptions = {};
            this.gridOptions.rowData = this.createRowData();
            this.gridOptions.columnDefs = this.createColumnDefs();
            this.gridOptions.rowDragManaged = true;
        }
    }
</script>
```

**Comment by smpita** [comment] 2018-05-18 17:08
+1

**Comment by lhilton** [comment] 2018-06-15 18:06
Anyone have a moment to look at this? I am unable to use row dragging in my own project, and the example integration I noted is still failing as of 18.0.1

**Comment by AntonioRecaldeRusso** [comment] 2019-04-01 05:06
I am having this issue uising react with `ag-grid-enterprise 20.1.0`.
The rows are not draggable, and the drag icon is not rendered

**Comment by cjstage** [comment] 2019-07-20 17:19
Having the same issue with ag-grid vue.  Anyone find a fix for this?

**Comment by seanlandsman** [comment] 2019-12-04 14:01
Hi

I am unable to reproduce this as of version 22. If you believe that this is still an issue please feel free to raise a new issue along with a working example of the problem.

**Closed by seanlandsman** 2019-12-04 14:01 UTC
